import React from 'react'

export const metadata = {
  title: "Contact Us - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {

  return (
    <div>
      
    </div>
  )
}
